apiVersion: v1
kind: Service
metadata:
  name: ordenes-api-svc
spec:
  type: NodePort
  selector:
    app: ordenes-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080